[package]
name = "jest_workaround"
version = "0.1.4"
edition = "2021"
authors = ["magic-akari <akari.ccino@gmail.com>"]
description = "[SWC plugin] workaround for jest"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/magic-akari/jest_workaround"
repository = "https://github.com/magic-akari/jest_workaround"
keywords = ["swc-plugin", "jest"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
indexmap = "1"
serde = "1"
swc_common = "0.24"
swc_plugin = "0.82"

[dev-dependencies]
swc_ecma_transforms_base = "0.98"
swc_ecma_transforms_testing = "0.100"
testing = "0.26"

[profile.release]
strip = "debuginfo"
