name: Cron Test

on:
    schedule:
        - cron: "0 0,12 * * *"

env:
    CARGO_INCREMENTAL: 0
    RUST_LOG: "debug"
    DIFF: 0
    RUST_MIN_STACK: 4194304
    NODE_ENV: "development"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  target: wasm32-unknown-unknown

            - uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - uses: pnpm/action-setup@v2.2.2

            - run: pnpm add -D --ignore-scripts @swc/core@latest @swc/jest@latest jest@latest
            - run: cargo build --target wasm32-unknown-unknown
            - run: pnpm test
